.TH init 8 "September 2006" "Upstart"
.\"
.SH NAME
init \- process management daemon
.\"
.SH SYNOPSIS
\fBinit\fR [\fIOPTION\fR]...
.\"
.SH DESCRIPTION
.B init
is the parent of all processes on the system, it is executed by the kernel
and is responsible for starting all other processes.
.\"
.SH NOTES
This manual page is temporary, you may have been looking for the
.BR telinit (8)
manual page.
.\"
.SH AUTHOR
Written by Scott James Remnant.
.\"
.SH REPORTING BUGS
Report bugs at https://launchpad.net/products/upstart/+bugs
.\"
.SH COPYRIGHT
Copyright \(co 2006 Canonical Ltd.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.\"
.SH SEE ALSO
.BR telinit (8)
