.TH upstart\-local\-bridge 8 2013-07-23 upstart
.\"
.SH NAME
upstart\-local\-bridge \- Bridge between Upstart and a local client socket
connection.
.\"
.SH SYNOPSIS
.B upstart\-local\-bridge
.RI [ OPTIONS ]...
.\"
.SH DESCRIPTION
.B upstart\-local\-bridge
listens on a local domain socket for name=value pairs and creates
.BR init (8)
events for them.

The local unix domain socket can be either named or abstract.
.\"
.SH OPTIONS
.\"
.TP
.B \-\-any\-user
By default the bridge will only accept connections from clients running
under the same user ID as the bridge itself. This option allows
connections from any user.
.\"
.TP
.B \-\-daemon
Detach and run in the background.
.\"
.TP
.B \-\-debug
Enable debugging output.
.\"
.TP
.B \-\-event \fIevent\fP
Specify name of event to emit on receipt of a name=value pair.
.\"
.TP
.B \-\-help
Show brief usage summary.
.\"
.TP
.B \-\-path \fIpath\fP
Specify path for local/abstract socket to listen on. If the first byte of
.I path
is an \(aq\fI@\fP\(aq, the socket will be created as an abstract socket.
.\"
.TP
.B \-\-verbose
Enable verbose output.
.\"
.SH EVENT DETAILS

The following environment variables are added automatically to the event
to be emitted, with the name=value pair being added as the last variable.
.P
.IP \(bu 4
SOCKET_TYPE=unix
.IP \(bu 4
SOCKET_VARIANT=[\fInamed\fP|\fIabstract\fP]
Sub-type of socket.
.IP \(bu 4
CLIENT_UID=\fIUID\fP
User ID of connected client.
.IP \(bu 4
CLIENT_GID=\fIGID\fP
Group ID of connected client.
.IP \(bu 4
CLIENT_PID=\fIPID\fP
Process ID of connected client.
.IP \(bu 4
PATH=\fIPATH\fP
.P
.\"
.SH EXAMPLES
.IP "upstart\-local\-bridge \-\-event=foo \-\-path=/var/foo/bar" 0.4i
Listen on local socket
.I /var/foo/bar
and when a name=value pair is read, emit an event of the form:

.RS
.nf
foo SOCKET_TYPE=unix SOCKET_VARIANT=named PATH=/var/foo/bar name=value
.fi
.RE
.IP "upstart\-local\-bridge \-\-event=bar \-\-path=@/var/foo/bar" 0.4i
Listen on abstract socket
.I @/var/foo/bar
and when a name=value pair is read, emit an event of the form:

.RS
.nf
bar SOCKET_TYPE=unix SOCKET_VARIANT=abstract PATH=@/var/foo/bar name=value
.fi
.RE
.\"
.SH NOTES
.IP \(bu 4
If a named local socket is specified, all path elements except
for the last must already exist before the bridge starts.
.\"
.SH LIMITATIONS

.IP \(bu 4
Only a single client connection is serviced at any one time.
.\"
.SH AUTHOR
Written by James Hunt
.RB < james.hunt@canonical.com >
.\"
.SH BUGS
Report bugs at 
.RB < https://launchpad.net/ubuntu/+source/upstart/+bugs >
.\"
.SH COPYRIGHT
Copyright \(co 2013 Canonical Ltd.
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH SEE ALSO
.BR init (5)
.BR init (8)
