debian/conf/*.conf etc/init/
etc/init/*.conf
etc/dbus-1/system.d/Upstart.conf
sbin/halt
sbin/poweroff
sbin/reboot
sbin/runlevel
sbin/shutdown
sbin/upstart-socket-bridge
debian/upstart-job lib/init/
debian/migrate-inittab.pl usr/lib/upstart/
usr/share/man/man7/control-alt-delete.7
usr/share/man/man7/keyboard-request.7
usr/share/man/man7/runlevel.7
usr/share/man/man7/socket-event.7
usr/share/man/man7/power-status-changed.7
usr/share/man/man8/shutdown.8
usr/share/man/man8/runlevel.8
usr/share/man/man8/reboot.8
usr/share/man/man8/upstart-socket-bridge.8
usr/share/man/man8/telinit.8
usr/share/man/man5/inittab.5
usr/share/man/man7/net-device-added.7
usr/share/man/man7/drm-device-added.7
usr/share/man/man7/graphics-device-added.7
usr/share/man/man7/net-device-removed.7
usr/share/man/man8/poweroff.8
usr/share/man/man8/halt.8
